<?php

declare(strict_types=1);

namespace App\Tests\Support\Step\Acceptance;

/*
 * Step Objects are a layer of abstraction over the Actor class. They are used to group common actions together and make your 
 * tests more readable and maintainable. They are similar to Page Objects, but they are not tied to a specific page. They can 
 * be used to represent a user role, a workflow, or any other concept that makes sense in your application. 
 * 
 * This file is generated by `php vendor/bin/codecept generate:stepobject Acceptance Admin` command.
 * 
 */
class Admin extends \App\Tests\Support\AcceptanceTester
{
    public function signUpAsAdmin()
    {
        $I = $this;

        $I->fillField('username', 'admin@example.com');
        $I->fillField('password', new \Codeception\Step\Argument\PasswordArgument('password123')); 
        $I->selectOption('gender', 'male');
        $I->checkOption('agree-terms');

        $I->click('Sign Up');
    }
}
