<?php

declare(strict_types=1);

namespace App\Tests\Support\Page\Acceptance;

/*
 * In Codeception, you can create Page Objects to represent pages of your application. They are used to group actions,
 * which can be performed on a page, and elements of the page. This way, you can reuse the code for interacting with the 
 * page in different tests, and keep your test code clean and readable.
 * 
 * This file is generated by `php vendor/bin/codecept generate:pageobject Acceptance Signup` command.
 * 
 * It is recommended to use page objects for acceptance testing only, as they are designed to work with the WebDriver module. 
 * For functional testing, you can use the same approach, but it is not required.
 * 
 */
class Signup
{
    public static $URL = '/signup';

    public $usernameField      = '#signup-form #username';
    public $passwordField      = '#signup-form #password';
    public $genderSelect       = '#signup-form #gender';
    public $agreeTermsCheckbox = '#signup-form #agree-terms';
    public $signupButton       = '#signup-form button[type=submit]';

    /**
     * Declare UI map for this page here. CSS or XPath allowed.
     * public $usernameField = '#username';
     * public $formSubmitButton = "#mainForm input[type=submit]";
     */

    /**
     * @var \App\Tests\Support\AcceptanceTester
     */
    protected $acceptanceTester;

    public function __construct(\App\Tests\Support\AcceptanceTester $I)
    {
        $this->acceptanceTester = $I;
        // you can inject other page objects here as well
    }

    public function signup(string $name, string $password, string $gender, bool $agreeTerms)
    {
        $I = $this->acceptanceTester;

        $I->amOnPage(self::$URL);
        
        $I->fillField($this->usernameField, $name);
        $I->fillField($this->passwordField, new \Codeception\Step\Argument\PasswordArgument($password));
        $I->selectOption($this->genderSelect, $gender);
        
        if ($agreeTerms) {
            $I->checkOption($this->agreeTermsCheckbox);
        } else {
            $I->uncheckOption($this->agreeTermsCheckbox);
        }

        $I->click($this->signupButton);
    }
}
